### ISSUE TITLE
Open this repository

### ISSUE THREAD

**Issue by cataphract** [DataDog/libddwaf-java#31]
- [x] Add NOTICE file (see #34)
- [x] Chose license and add LICENSE file (see #32)
- [x] Make sure README is up-to-date (see #37)
- [x] Add CONTRIBUTING (see #38)
- [x] Add .github/ISSUE_TEMPLATE/bug_report.md (see #35)
- [x] Add .github/PULL_REQUEST_TEMPLATE/pull_request_template.md (see #35)
- [x] The repository must contain a complete list of third party open source components (see #32 )
- [x] Ensure that all included 3rd party code is compliant with the license used for the repository and remedy if it is not.
- [x] Ensure there are no tokens, keys, or other sensitive data in the repository. If appropriate, reach out to `#security` and they will verify.
- [x] Each file should include copyright header (see #33):
```
Unless explicitly stated otherwise all files in this repository are licensed
under the $license_for_repo License.

This product includes software developed at Datadog
(https://www.datadoghq.com/). Copyright $year Datadog, Inc.
```
